compile_world:
	g++ -std=c++11 -o mWorld mWorld.cpp ../implementation/Hewan.cpp ../implementation/KeyPressHandler.cpp ../implementation/LMakhluk.cpp ../implementation/Makhluk.cpp ../implementation/Matrix.cpp ../implementation/Point.cpp ../implementation/PolarBear.cpp ../implementation/Snake.cpp ../implementation/Rabbit.cpp ../implementation/RandomGenerator.cpp ../implementation/Screen.cpp ../implementation/Sheep.cpp ../implementation/Tumbuhan.cpp ../implementation/Turtle.cpp ../implementation/Wolf.cpp ../implementation/World.cpp ../implementation/WorldBuilder.cpp ../implementation/IOManager.cpp ../implementation/SnapshotCapturer.cpp ../implementation/ExceptionObject.cpp ../implementation/MakhlukLive.cpp

run_world:
	mWorld

compile_random_generator:
	g++ -std=c++11 -o mRandomGenerator mRandomGenerator.cpp ../implementation/RandomGenerator.cpp ../implementation/Point.cpp
	
run_random_generator:
	mRandomGenerator
