compile_matrix:
	g++ -std=c++11 -o mMatrix mMatrix.cpp ../implementation/Matrix.cpp

run_matrix:
	mMatrix

compile_world:
	g++ -std=c++11 -o mWorld mWorld.cpp ../implementation/Point.cpp ../implementation/LMakhluk.cpp ../implementation/World.cpp ../implementation/Makhluk.cpp ../implementation/Matrix.cpp ../implementation/PolarBear.cpp ../implementation/Hewan.cpp ../implementation/KeypressHandler.cpp ../implementation/Rabbit.cpp ../implementation/Turtle.cpp

run_world:
	mWorld
	
compile_point:
	g++ -std=c++11 -o mPoint mPoint.cpp ../implementation/Point.cpp
	
run_point:
	mPoint
