compile_matrix:
	g++ -o mMatrix mMatrix.cpp ../implementation/*.cpp

run_matrix:
	mMatrix

compile_world:
	g++ -o mWorld mWorld.cpp ../implementation/*.cpp

run_world:
	mWorld
	
compile_point:
	g++ -o mPoint mPoint.cpp ../implementation/*.cpp
	
run_point:
	mPoint
