compile_matrix:
	g++ -std=c++11 -o mMatrix mMatrix.cpp ../implementation/Matrix.cpp

run_matrix:
	mMatrix
	
compile_point:
	g++ -std=c++11 -o mPoint mPoint.cpp ../implementation/Point.cpp
	
run_point:
	mPoint
	
compile_world:
	g++ -std=c++11 -o mWorld mWorld.cpp ../implementation/Hewan.cpp ../implementation/KeyPressHandler.cpp ../implementation/LMakhluk.cpp ../implementation/Makhluk.cpp ../implementation/Matrix.cpp ../implementation/Point.cpp ../implementation/PolarBear.cpp ../implementation/Rabbit.cpp ../implementation/RandomGenerator.cpp ../implementation/Screen.cpp ../implementation/Sheep.cpp ../implementation/Tumbuhan.cpp ../implementation/Turtle.cpp ../implementation/Wolf.cpp ../implementation/World.cpp ../implementation/WorldBuilder.cpp

run_world:
	mWorld