compile_matrix:
	g++ -std=c++11 -o mMatrix mMatrix.cpp ../implementation/Matrix.cpp

run_matrix:
	mMatrix
	
compile_point:
	g++ -std=c++11 -o mPoint mPoint.cpp ../implementation/Point.cpp
	
run_point:
	mPoint
	
compile_world:
	g++ -std=c++11 -o mWorld mWorld.cpp ../implementation/Hewan.cpp ../implementation/KeyPressHandler.cpp ../implementation/LMakhluk.cpp ../implementation/Makhluk.cpp ../implementation/Matrix.cpp ../implementation/Point.cpp ../implementation/PolarBear.cpp ../implementation/Rabbit.cpp ../implementation/RandomGenerator.cpp ../implementation/Screen.cpp ../implementation/Sheep.cpp ../implementation/Tumbuhan.cpp ../implementation/Turtle.cpp ../implementation/Wolf.cpp ../implementation/World.cpp ../implementation/WorldBuilder.cpp ../implementation/IOManager.cpp ../implementation/SnapshotCapturer.cpp ../implementation/ExceptionObject.cpp

run_world:
	mWorld

compile_screen:
	g++ -std=c++11 -o mScreen mScreen.cpp ../implementation/Hewan.cpp ../implementation/KeyPressHandler.cpp ../implementation/LMakhluk.cpp ../implementation/Makhluk.cpp ../implementation/Matrix.cpp ../implementation/Point.cpp ../implementation/PolarBear.cpp ../implementation/Rabbit.cpp ../implementation/RandomGenerator.cpp ../implementation/Screen.cpp ../implementation/Sheep.cpp ../implementation/Tumbuhan.cpp ../implementation/Turtle.cpp ../implementation/Wolf.cpp ../implementation/World.cpp ../implementation/WorldBuilder.cpp ../implementation/IOManager.cpp ../implementation/SnapshotCapturer.cpp

run_screen:
	mScreen

compile_snapshot_capturer:
	g++ -std=c++11 -o mSnapshotCapturer mSnapshotCapturer.cpp ../implementation/Hewan.cpp ../implementation/KeyPressHandler.cpp ../implementation/LMakhluk.cpp ../implementation/Makhluk.cpp ../implementation/Matrix.cpp ../implementation/Point.cpp ../implementation/PolarBear.cpp ../implementation/Rabbit.cpp ../implementation/RandomGenerator.cpp ../implementation/Screen.cpp ../implementation/Sheep.cpp ../implementation/Tumbuhan.cpp ../implementation/Turtle.cpp ../implementation/Wolf.cpp ../implementation/World.cpp ../implementation/WorldBuilder.cpp ../implementation/IOManager.cpp ../implementation/SnapshotCapturer.cpp

run_snapshot_capturer:
	mSnapshotCapturer

compile_keypress_handler:
	g++ -std=c++11 -o mKeypressHandler mKeypressHandler.cpp ../implementation/Hewan.cpp ../implementation/KeyPressHandler.cpp ../implementation/LMakhluk.cpp ../implementation/Makhluk.cpp ../implementation/Matrix.cpp ../implementation/Point.cpp ../implementation/PolarBear.cpp ../implementation/Rabbit.cpp ../implementation/RandomGenerator.cpp ../implementation/Screen.cpp ../implementation/Sheep.cpp ../implementation/Tumbuhan.cpp ../implementation/Turtle.cpp ../implementation/Wolf.cpp ../implementation/World.cpp ../implementation/WorldBuilder.cpp ../implementation/IOManager.cpp ../implementation/SnapshotCapturer.cpp

run_keypress_handler:
	mKeypressHandler

compile_world_builder:
	g++ -std=c++11 -o mWorldBuilder mWorldBuilder.cpp ../implementation/Hewan.cpp ../implementation/KeyPressHandler.cpp ../implementation/LMakhluk.cpp ../implementation/Makhluk.cpp ../implementation/Matrix.cpp ../implementation/Point.cpp ../implementation/PolarBear.cpp ../implementation/Rabbit.cpp ../implementation/RandomGenerator.cpp ../implementation/Screen.cpp ../implementation/Sheep.cpp ../implementation/Tumbuhan.cpp ../implementation/Turtle.cpp ../implementation/Wolf.cpp ../implementation/World.cpp ../implementation/WorldBuilder.cpp ../implementation/IOManager.cpp ../implementation/SnapshotCapturer.cpp ../implementation/ExceptionObject.cpp

run_world_builder:
	mWorldBuilder

compile_exception_object:
	g++ -std=c++11 -o mExceptionObject mExceptionObject.cpp ../implementation/ExceptionObject.cpp

run_exception_object:
	mExceptionObject